/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMyIndexRouteImport } from './routes/_authenticated/my.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedMyTrendsRouteImport } from './routes/_authenticated/my.trends'
import { Route as AuthenticatedMyRentersRouteImport } from './routes/_authenticated/my.renters'
import { Route as AuthenticatedMyListRouteImport } from './routes/_authenticated/my.list'
import { Route as AuthenticatedAdminTrendsRouteImport } from './routes/_authenticated/admin.trends'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRentersRouteImport } from './routes/_authenticated/admin.renters'
import { Route as AuthenticatedAdminAssetsRouteImport } from './routes/_authenticated/admin.assets'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin.settings.index'
import { Route as AuthenticatedAdminSettingsUploadRouteImport } from './routes/_authenticated/admin.settings.upload'
import { Route as AuthenticatedAdminSettingsAccountsRouteImport } from './routes/_authenticated/admin.settings.accounts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyIndexRoute = AuthenticatedMyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMyTrendsRoute = AuthenticatedMyTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedMyRentersRoute = AuthenticatedMyRentersRouteImport.update({
  id: '/renters',
  path: '/renters',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedMyListRoute = AuthenticatedMyListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthenticatedMyRoute,
} as any)
const AuthenticatedAdminTrendsRoute =
  AuthenticatedAdminTrendsRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRentersRoute =
  AuthenticatedAdminRentersRouteImport.update({
    id: '/renters',
    path: '/renters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssetsRoute =
  AuthenticatedAdminAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsUploadRoute =
  AuthenticatedAdminSettingsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsAccountsRoute =
  AuthenticatedAdminSettingsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my': typeof AuthenticatedMyRouteWithChildren
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/renters': typeof AuthenticatedAdminRentersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/trends': typeof AuthenticatedAdminTrendsRoute
  '/my/list': typeof AuthenticatedMyListRoute
  '/my/renters': typeof AuthenticatedMyRentersRoute
  '/my/trends': typeof AuthenticatedMyTrendsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/my/': typeof AuthenticatedMyIndexRoute
  '/admin/settings/accounts': typeof AuthenticatedAdminSettingsAccountsRoute
  '/admin/settings/upload': typeof AuthenticatedAdminSettingsUploadRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/renters': typeof AuthenticatedAdminRentersRoute
  '/admin/trends': typeof AuthenticatedAdminTrendsRoute
  '/my/list': typeof AuthenticatedMyListRoute
  '/my/renters': typeof AuthenticatedMyRentersRoute
  '/my/trends': typeof AuthenticatedMyTrendsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/my': typeof AuthenticatedMyIndexRoute
  '/admin/settings/accounts': typeof AuthenticatedAdminSettingsAccountsRoute
  '/admin/settings/upload': typeof AuthenticatedAdminSettingsUploadRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/my': typeof AuthenticatedMyRouteWithChildren
  '/_authenticated/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/_authenticated/admin/renters': typeof AuthenticatedAdminRentersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/trends': typeof AuthenticatedAdminTrendsRoute
  '/_authenticated/my/list': typeof AuthenticatedMyListRoute
  '/_authenticated/my/renters': typeof AuthenticatedMyRentersRoute
  '/_authenticated/my/trends': typeof AuthenticatedMyTrendsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/my/': typeof AuthenticatedMyIndexRoute
  '/_authenticated/admin/settings/accounts': typeof AuthenticatedAdminSettingsAccountsRoute
  '/_authenticated/admin/settings/upload': typeof AuthenticatedAdminSettingsUploadRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/my'
    | '/admin/assets'
    | '/admin/renters'
    | '/admin/settings'
    | '/admin/trends'
    | '/my/list'
    | '/my/renters'
    | '/my/trends'
    | '/admin/'
    | '/my/'
    | '/admin/settings/accounts'
    | '/admin/settings/upload'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/assets'
    | '/admin/renters'
    | '/admin/trends'
    | '/my/list'
    | '/my/renters'
    | '/my/trends'
    | '/admin'
    | '/my'
    | '/admin/settings/accounts'
    | '/admin/settings/upload'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/my'
    | '/_authenticated/admin/assets'
    | '/_authenticated/admin/renters'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/trends'
    | '/_authenticated/my/list'
    | '/_authenticated/my/renters'
    | '/_authenticated/my/trends'
    | '/_authenticated/admin/'
    | '/_authenticated/my/'
    | '/_authenticated/admin/settings/accounts'
    | '/_authenticated/admin/settings/upload'
    | '/_authenticated/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my/': {
      id: '/_authenticated/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof AuthenticatedMyIndexRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/my/trends': {
      id: '/_authenticated/my/trends'
      path: '/trends'
      fullPath: '/my/trends'
      preLoaderRoute: typeof AuthenticatedMyTrendsRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/my/renters': {
      id: '/_authenticated/my/renters'
      path: '/renters'
      fullPath: '/my/renters'
      preLoaderRoute: typeof AuthenticatedMyRentersRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/my/list': {
      id: '/_authenticated/my/list'
      path: '/list'
      fullPath: '/my/list'
      preLoaderRoute: typeof AuthenticatedMyListRouteImport
      parentRoute: typeof AuthenticatedMyRoute
    }
    '/_authenticated/admin/trends': {
      id: '/_authenticated/admin/trends'
      path: '/trends'
      fullPath: '/admin/trends'
      preLoaderRoute: typeof AuthenticatedAdminTrendsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/renters': {
      id: '/_authenticated/admin/renters'
      path: '/renters'
      fullPath: '/admin/renters'
      preLoaderRoute: typeof AuthenticatedAdminRentersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assets': {
      id: '/_authenticated/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AuthenticatedAdminAssetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/upload': {
      id: '/_authenticated/admin/settings/upload'
      path: '/upload'
      fullPath: '/admin/settings/upload'
      preLoaderRoute: typeof AuthenticatedAdminSettingsUploadRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings/accounts': {
      id: '/_authenticated/admin/settings/accounts'
      path: '/accounts'
      fullPath: '/admin/settings/accounts'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
  }
}

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsAccountsRoute: typeof AuthenticatedAdminSettingsAccountsRoute
  AuthenticatedAdminSettingsUploadRoute: typeof AuthenticatedAdminSettingsUploadRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsAccountsRoute:
      AuthenticatedAdminSettingsAccountsRoute,
    AuthenticatedAdminSettingsUploadRoute:
      AuthenticatedAdminSettingsUploadRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssetsRoute: typeof AuthenticatedAdminAssetsRoute
  AuthenticatedAdminRentersRoute: typeof AuthenticatedAdminRentersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminTrendsRoute: typeof AuthenticatedAdminTrendsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssetsRoute: AuthenticatedAdminAssetsRoute,
  AuthenticatedAdminRentersRoute: AuthenticatedAdminRentersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminTrendsRoute: AuthenticatedAdminTrendsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMyRouteChildren {
  AuthenticatedMyListRoute: typeof AuthenticatedMyListRoute
  AuthenticatedMyRentersRoute: typeof AuthenticatedMyRentersRoute
  AuthenticatedMyTrendsRoute: typeof AuthenticatedMyTrendsRoute
  AuthenticatedMyIndexRoute: typeof AuthenticatedMyIndexRoute
}

const AuthenticatedMyRouteChildren: AuthenticatedMyRouteChildren = {
  AuthenticatedMyListRoute: AuthenticatedMyListRoute,
  AuthenticatedMyRentersRoute: AuthenticatedMyRentersRoute,
  AuthenticatedMyTrendsRoute: AuthenticatedMyTrendsRoute,
  AuthenticatedMyIndexRoute: AuthenticatedMyIndexRoute,
}

const AuthenticatedMyRouteWithChildren = AuthenticatedMyRoute._addFileChildren(
  AuthenticatedMyRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMyRoute: typeof AuthenticatedMyRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMyRoute: AuthenticatedMyRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
